### ISSUE TITLE
这个双拼评测工具"双拼方案评测和优化",为什么不能定义“零声母”呢？

### ISSUE THREAD

**Issue by zgdlime** [macroxue/shuangpin#1]
@macroxue 这个双拼评测工具"双拼方案评测和优化",为什么不能定义“零声母”呢？

零声母也是双拼布局的组成部分吧！可由不同字母引导呢（AEOUIV）;

**Comment by macroxue** [comment]
commit 0e92555299a69792a8481cffedfbec26ada7724e 添加了关于零声母的声明。

可以呀，零声母以‘0’表示，比如微软方案零声母在‘O'键上。

**Comment by zgdlime** [comment]
@macroxue 额，我定制了一个双拼方案，想使用两个字母分别引导不同的零声母，
举个例：在拼音加加方案里，我想由字母R引导er，其他零声母由字母J引导，
那又如何设定呢？

**Comment by zgdlime** [comment]
还有一个问题：看不出“加加”和“小鹤”这两个双拼的不同的零声母，设置位置？

**Comment by macroxue** [comment]
> @macroxue 额，我定制了一个双拼方案，想使用两个字母分别引导不同的零声母，
> 举个例：在拼音加加方案里，我想由字母R引导er，其他零声母由字母J引导，
> 那又如何设定呢？

不好意思，该工具只支持一个零声母，多个零声母定义起来相当麻烦。

> 还有一个问题：看不出“加加”和“小鹤”这两个双拼的不同的零声母，设置情况？

如果没有搞错的话，加加和小鹤的零声母方案是重复韵母的第一个音，比如加加：案=an=a+f。这虽然是多个零声母，但是零声母是由韵母导出，和完全的自定义并不相同。
