### ISSUE TITLE
希望评测工具能增加对Colemak-DH的支持

### ISSUE THREAD

**Issue by pingshunhuangalex** [macroxue/shuangpin#3]
希望评测工具能增加对Colemak-DH的支持 谢谢

另外最后的得分不是很懂 似乎全拼的得分永远是最高的…… 得分难道不是越高越好吗？

**Comment by macroxue** [comment]
各种 mod 方案很多，不便一一加入，还请见谅。或许你可以直接修改evaluator.js？

最后的得分评的是舒适度，全拼很舒适，但是击键次数多、打得慢。

**Comment by pingshunhuangalex** [comment]
谢谢回复

那能否增加一个布局的自定义模式？

如果我需要查看击键次数少 速度最快 且把常用声韵母放在home row且考虑手指灵活性和连击的话应该查看哪像项值呢？谢谢

**Comment by macroxue** [comment]
这个功能已经有了，只是不太明显。所有声母的位置都可以自定义，具体例子请参见‘乱序优化’方案。
