### ISSUE TITLE
火星双拼，有创意，提个问题：

### ISSUE THREAD

**Issue by wwzrh** [macroxue/shuangpin#4]
火星双拼，有创意，提个问题：
①单字重码不是很高了吗？例如uai和ai都定义在R,F,V，g与uai和ai会产生很多单字的重码。
    - xform/u?ai[4]:/R/
    - xform/u?ai[23]:/F/
    - xform/u?ai[15]:/V/
②键位图ou分布在a，en在s，ei在d，eng和ai在f，an在g，ang在h，er在k，ong在l，ao在；，分布依据是什么呢？
为什么j键空的？
③在方案里的正则表达式中=和/一样吗？请教如下：
    - xform/i?ao[4]:/P/
    - xform/i?ao[23]:/;/
    - xform=i?ao[15]:=/=

**Comment by macroxue** [comment]
① 单字重码可以用辅助码消除。普通双拼只有400个有效编码，火星双拼则有645个，7000个汉字分布在645个编码上的平均重码率更低。

② 键位的分布的依据是尽量减少动态重码。比如 ou 也可以在 J 键上，但是会和韵母 u 有较多的冲突。按键舒适度也有考虑，但不是主要目标。

③ 正则表达式中的分隔符可以是任意符号。这里用 = 是为了避免和表示键位的 / 冲突。
