### ISSUE TITLE
“双拼方案评测、优化和生成”請求增加自定義音節功能，以計算飛鍵影響

### ISSUE THREAD

**Issue by Cyoudgax** [macroxue/shuangpin#5]
聲母韻母分開填寫無法測量飛鍵，一些強制飛鍵方案，如：
B鍵（聲母b、韻母ie）、C鍵（聲母c、韻母o）、P鍵（0聲母、韻母o）
現測評無法指定拼音bo的鍵位爲B鍵+P鍵。
因音節數量沒有定論，可設置由用戶先自定義每個音節，再統計總數後測評。

**Comment by macroxue** [comment]
曾考虑过支持飞键，原则上可以实现。当有多个按键可选择时，总是选代价最小的那一个。
不过我现在没时间增加这个功能，年底时再看看吧，不好意思。

**Comment by macroxue** [comment]
已在 386559a21914dfe6271fdb9a83f64c879801eb30 中支持飞键。
