### ISSUE TITLE
希望增加几个键盘布局

### ISSUE THREAD

**Issue by lenny20** [macroxue/shuangpin#6]
首先感谢分享好工具！
目前看到只有3种键盘布局，不够用。
希望增加workman、minimak、halmak、Engram、qgmlwb(carpalx)这几种更优秀的键盘布局。
我下载master添加后无法加载，一片空白。

**Comment by lenny20** [comment]
这里有一些新式键盘布局，希望支持：
http://xahlee.info/kbd/dvorak_and_all_keyboard_layouts.html

**Comment by macroxue** [comment]
键盘布局在工具里可以自行定义，请参考“乱序优化”方案。
