### ISSUE TITLE
请教一下全拼分数

### ISSUE THREAD

**Issue by luminosara** [macroxue/shuangpin#9]
请教一下为什么全拼的分数要比大部分双拼的方案分数高，是因为全拼的速度还是要比双拼快吗，还是需要考虑其他的因素？

长文，全拼分数

![image](https://github.com/macroxue/shuangpin/assets/87697012/b7f55461-7543-42fc-98f4-7626e1d776d4)

长文，UAI分数

![image](https://github.com/macroxue/shuangpin/assets/87697012/3093473e-b86a-4f50-bbb1-63bc73a07d42)

默认，全拼分数

![image](https://github.com/macroxue/shuangpin/assets/87697012/3bff5ed8-26aa-4f6a-9fd1-8fa5bdce5677)

默认，UAI优化结果

![image](https://github.com/macroxue/shuangpin/assets/87697012/f3a7a5f2-9d80-4cc4-afe4-78d4054aabe5)

**Comment by lenny20** [comment]
全拼相当于打英文字母，可以优化到210分，例如 https://zhuanlan.zhihu.com/p/671465361
双拼有很多同手连击甚至同指连击，评分必然要低一截，乱序排布也最多185分。

**Comment by lenny20** [comment]
双拼与全拼的重码率一样，并无关系。
双拼比全拼快是因为两键一字。
降低重码率的方法是使用自然码/小鹤这些带偏旁辅助码的输入方案。

**Comment by macroxue** [comment]
全拼的确比一些不够优化的双拼顺手，不过每字按键较多，所以输入效率较低。以如下数据为例，全拼击键数约是双拼加加的1.5倍，而时间约是1.4倍。

加加：击键数 701804，时间 562171
全拼：击键数 1039692，时间 781943

**Comment by macroxue** [comment]
嗯，我考虑一下。现在的分数代表的是击键的速度，而不是汉字的录入速度，确实有点绕。

**Comment by macroxue** [comment]
尚在犹豫中…… 

现有公式：得分 = 击键数 ÷ 时间 × 100

如果要让全拼分数降下来，新的算分公式是：得分 = 字数 ÷ 时间 × 100 

中文字数好算，英文是算字母数还是单词数呢？如果算字母数，英文键盘的得分通常是双拼键盘的两倍。如果算单词数，英文键盘的得分反而成了一半。

**Comment by lenny20** [comment]
英文算字母数吧，因为有一些无法估算的省写，还有各种代码。

**Comment by macroxue** [comment]
1f24a9e2936cb4ec812b7cbbfcc5dd45a43bb5b0 基于录入字数计算得分

**Comment by luminosara** [comment]
新年快乐！多谢大家参与贡献！如果没有另外的讨论，我就close啦
